### ISSUE TITLE
dependencytrack/apiserver status unhealthy

### ISSUE THREAD

**Issue by lightjw** [DependencyTrack/dependency-track#1388]
Hello, I tried to install dependency-track, but apiserver is unhealthy.
I can't see the problem through the log.
How can I locate the problem.
thanks.

1. install
```
curl -LO https://dependencytrack.org/docker-compose.yml
docker-compose up -d
```

2. docker ps
```
3f0eef35fcb1   dependencytrack/apiserver   "/bin/sh -c 'java $J…"   20 minutes ago   Up 20 minutes (unhealthy)   0.0.0.0:8081->8080/tcp   gitlab_dtrack-apiserver_1
7d9e009049c1   dependencytrack/frontend    "/docker-entrypoint.…"   2 days ago       Up 2 hours                  0.0.0.0:8080->8080/tcp   gitlab_dtrack-frontend_1
```

3. docker logs 
![image](https://user-images.githubusercontent.com/42208084/153794963-dc0236f6-4616-449b-9650-00bb2363a063.png)

**Comment by lordpayder** [comment]
Same Problem with Version 4.4.0 from Dockerhub.
Seems like the Healthcheck is using wget, but wget is not installed.

**Comment by DanielRuf** [comment]
Still not fixed when I use podman. The docker-compose file is missing a healthcheck for the apiserver.

**Comment by DanielRuf** [comment]
I have fixed it with the following changes:

```diff
  apiserver:
    image: dependencytrack/apiserver
    healthcheck:
      test: [ "CMD", "wget", "--no-proxy -q -O /dev/null", "http://127.0.0.1:8080/api/version" ]
      interval: 5s
      timeout: 3s
```

Where is this file that is hosted on the website, so we can provide a PR?
If it is https://github.com/DependencyTrack/dependency-track/blob/master/src/main/docker/docker-compose.yml, how does it get copied to the website?

**Comment by DanielRuf** [comment]
I have fixed it with the following changes:

```diff
  apiserver:
    image: dependencytrack/apiserver
    healthcheck:
      test: [ "CMD", "wget", "--no-proxy -q -O /dev/null", "http://127.0.0.1:8080/api/version" ]
      interval: 5s
      timeout: 3s
```

https://github.com/DependencyTrack/dependency-track/blob/master/src/main/docker/docker-compose.yml seems to be the correct file according to https://github.com/DependencyTrack/dependencytrack.org/blob/master/_redirects#L11C1-L11C131.

**Comment by DanielRuf** [comment]
I have fixed it with the following changes:

```diff
  apiserver:
    image: dependencytrack/apiserver
+    healthcheck:
+      test: [ "CMD", "wget", "--no-proxy -q -O /dev/null", "http://127.0.0.1:8080/api/version" ]
+      interval: 5s
+      timeout: 3s
```

https://github.com/DependencyTrack/dependency-track/blob/master/src/main/docker/docker-compose.yml seems to be the correct file according to https://github.com/DependencyTrack/dependencytrack.org/blob/master/_redirects#L11C1-L11C131.

**Comment by DanielRuf** [comment]
I can create a PR if someone can provide the recommended solution as comment.

**Comment by jasminmair** [comment]
Any feedback on the potential solution above? I am still encountering the same issue; although with the frontend container

**Comment by nscuro** [comment]
I am unable to replicate this unfortunately. There is a healthcheck defined in the `Dockerfile` which should be used by both Docker Compose and Podman Compose. If I execute the commands from the original post in this issue, I see:

```shell
$ docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED        STATUS                    PORTS                                         NAMES
6734d3b30bc2   dependencytrack/frontend        "/docker-entrypoint.…"   4 hours ago    Up 26 seconds             0.0.0.0:8080->8080/tcp, [::]:8080->8080/tcp   desktop-frontend-1
e80d52011e93   dependencytrack/apiserver       "/bin/sh -c 'exec ja…"   4 hours ago    Up 40 seconds (healthy)   0.0.0.0:8081->8080/tcp, [::]:8081->8080/tcp   desktop-apiserver-1
78387d26730c   postgres:17-alpine              "docker-entrypoint.s…"   4 hours ago    Up 46 seconds (healthy)   5432/tcp                                      desktop-postgres-1
```

If the health check is failing then that might indicate that the application itself is indeed down or failing to start.

@jasminmair From what I can see, the frontend container does not come with a predefined health check like the API server. So tools like Compose and k8s should just assume it's up.

**Comment by DanielRuf** [comment]
testp-apiserver-1 does actually run, it just seems the missing healthcheck in the docker-compose file seems to be relevant, at least for me.

**Comment by nscuro** [comment]
That might be a limitation of Podman Compose then. And that explains why I could not reproduce it. Docker Compose will pick up the health check from the container image, and really Podman Compose should do the same.
