### ISSUE TITLE
Frontend creates a lot of requests for projects with high amount of components

### ISSUE THREAD

**Issue by Blefish** [DependencyTrack/dependency-track#2255]
### Current Behavior

Browser is not able to handle so many requests and will start showing error messages.
![Screenshot from 2022-12-08 17-01-23](https://user-images.githubusercontent.com/1191779/206480993-0dc5913f-e61c-490d-b83d-54a71347507f.png)
![Screenshot from 2022-12-08 17-02-24](https://user-images.githubusercontent.com/1191779/206481031-b9adf1ca-893e-4824-bafc-dcf6755cad8d.png)
![Screenshot from 2022-12-08 17-03-03](https://user-images.githubusercontent.com/1191779/206481055-78a01ad4-5586-4c13-89b7-c2c634d8a5ac.png)

### Steps to Reproduce

1. Import SBOM into a project that has very many dependencies (for example, trivy SBOM of operating system)
2. Wait for SBOM to be imported and refresh the page

### Expected Behavior

I think it is loading information about all components with individual REST calls. It should be progressively loaded when navigating the pages in components view.

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

15.0

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by valentijnscholten** [comment]
I haven't seen errors but it is true that a call is being done for each component upon browsing to a project. In #2189 this is fixed/changed.

**Comment by Blefish** [comment]
Thanks, looks exactly like the fix, looking forward to it!

**Comment by rkg-mm** [comment]
@Blefish  this should be fixed with 4.7.0, can you confirm?

**Comment by Blefish** [comment]
Hi

I updated to 4.7.0, but it seems like unfortunately the issue still exists. I have a project with 1279 components. When opening the project (just clicking on the project name), frontend is creating a huge amount of requests to the backend.

Chrome is logging ERR_INSUFFICIENT_RESOURCES, that's when I see error messages in GUI, but most of them are continuing to run in the background, taking up roughly two minutes.

![Screenshot from 2022-12-21 10-58-34](https://user-images.githubusercontent.com/1191779/208863921-d24a4a59-c1d3-4b0a-b177-fa434f19346f.png)
![Screenshot from 2022-12-21 10-58-57](https://user-images.githubusercontent.com/1191779/208864670-27ac8a7d-82cc-4a3f-83d4-3a5ab619d3ad.png)

However, in the dependency graph view, it does seem like the issue is solved as I only see requests being made when I expand the child element.

**Comment by Blefish** [comment]
Attaching a sample SBOM for reference.
This is created with trivy on amazon linux 2 vagrant image:

```
vagrant init gbailey/amzn2
vagrant up
vagrant ssh
sudo -i
curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
/usr/local/bin/trivy rootfs / --format cyclonedx --output /tmp/sbom.cdx.json
```
[sbom.cdx.json.zip](https://github.com/DependencyTrack/dependency-track/files/10276313/sbom.cdx.json.zip)

**Comment by valentijnscholten** [comment]
Looks like this problem can still occur if you have a project where you have a large/huge number of direct dependencie, which is the case in the provided SBOM. I can see 350+ requests and 35MB+ of data when clicking on de project.

**Comment by rkg-mm** [comment]
Thats the data for the graph or? We should lazy-load the graph data when the tab opens

**Comment by nscuro** [comment]
It is already being lazy-loaded, unless the user wants to navigate directly to a component in the deeper layers of the graph. But even lazy-loading won't save you when the graph is huge.

**Comment by valentijnscholten** [comment]
Having a parameter (or new endpoint) that only provides the basic data needed for each component might help. But it might be better to have an endpoint that returns the dependencygraph in one call. This is also done for when viewing a "focussed" dependency graph from the Components tab. The initial view only needs the direct dependencies, deeper levels are already lazy loaded.

**Comment by valentijnscholten** [comment]
The dependency graph uses the same data. The current implementation is probably just a first implementation that has served well for a lot of projects that aren't too big.

**Comment by laurentpierson** [comment]
Hi, 

I'm also affected by this issue (using DT in version 4.7.1):

I have an SBOM with 1892 components. When opening the project page, 545MBs are downloaded:

![image](https://user-images.githubusercontent.com/1669973/224754402-f9300e3e-b983-4a47-9694-897ae9fe23f9.png)

**Comment by nathan-mittelette** [comment]
This behavior is due to the Dependency Graph that for each component/service link to the primary node a request will be made to the backend to get information at those endpoints : 

- GET `/api/v1/components/{uuid}`
- GET `/api/v1/services/{uuid}` 

There is the same behavior when a user click on the expand button.

To resolve this point, I propose to create one endpoint that can be called to fetch many components/services at the same time by giving a list of UUIDs.

It could be done in one endpoint that can return a list of components and services, or in two endpoints that can each return a list of services or a list of components.

I don't have a strong opinion about which one to implement.

**Comment by rkg-mm** [comment]
@AppSecAmael yes but the data is fetched already when the overview is opened. Which is optimization #1 to do: only load graph data when opening that tab.

Optimization #2 should be an endpoint to get all data from children of a specified level. Either root level (first request) or all children from a specific node. I would avoid passing lists of UUIDs, instead ask for a nodes children (or the root itself)

**Comment by Blefish** [comment]
At least in 4.8.0, I no longer see this problem with my BOM of over 1k components. I understand there might be more improvements? I see there is one more PR regarding this opened, so I will not close the issue for now, but at least on my end, the issue seems fixed.
